[RPD-164] Check whether remote state bucket has been provisioned
fuzzylabs/matcha pull request #106
Opened 2023-05-17 15:28 UTC by d-lowl

Check whether:
* State configuration is written and valid
* State bucket is provisioned

This PR adds new dependencies:

* `dataclasses-json = "^0.5.7"`
* `azure-storage-blob = "^12.16.0"`

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-05-19 09:31 UTC, dudeperf3ct requested changes
Excellent @d-lowl. Few missing docstring but implementation looks solid.

2023-05-19 09:31 UTC, dudeperf3ct commented on src/matcha_ml/state/remote_state_manager.py
> +    def _configuration_file_exists(self) -> bool:
Docstring missing

2023-05-19 09:31 UTC, dudeperf3ct commented on src/matcha_ml/state/remote_state_manager.py
> +    def _load_configuration(self) -> RemoteStateConfig:
Docstring missing

2023-05-19 09:31 UTC, dudeperf3ct commented on src/matcha_ml/state/remote_state_manager.py
>          Returns:
Missing docstring for `Raises`

2023-05-19 09:31 UTC, dudeperf3ct commented on src/matcha_ml/state/remote_state_manager.py
> +        If it was not initialized before, it will be initialized
Missing docstring for `Raises`

2023-05-19 09:31 UTC, dudeperf3ct commented on src/matcha_ml/storage/azure_storage.py
The implementation for `AzureStorage` will change as per PR #101

2023-05-22 07:14 UTC, dudeperf3ct approved these changes

2023-05-22 08:41 UTC, osw282 requested changes
One question and a missing arg in doc string, looks good otherwise.

2023-05-22 08:41 UTC, osw282 commented on src/matcha_ml/cli/cli.py
I thought we also need to check if the remote state storage is provisioned in the `provision` command too.

2023-05-22 08:41 UTC, osw282 commented on src/matcha_ml/state/remote_state_manager.py
> +        if config_path is not None:
Missing args in doc string.

2023-05-22 08:44 UTC, d-lowl commented on src/matcha_ml/cli/cli.py
We're checking the bucket's existence explicitly. I'm not sure if we actually need to check if terraform apply has ever been run.

2023-05-22 08:45 UTC, d-lowl commented on src/matcha_ml/state/remote_state_manager.py
> +import os.path
Used in __init__

2023-05-22 08:45 UTC, d-lowl commented on src/matcha_ml/state/remote_state_manager.py
> +        if config_path is not None:
Added in :+1:

2023-05-22 09:05 UTC, osw282 approved these changes
Well done, LGTM!! 🚀

2023-05-22 09:07 UTC, merged