[RPD-234] [BUG] Handle existing matcha configuration better
fuzzylabs/matcha pull request #135
Opened 2023-06-01 13:47 UTC by Christopher-Norman

When a user deletes a resource group manually or uses a shared state and another person has run `matcha destroy full` the user would be left with an out-of-sync config file. This would cause errors when running `matcha provision` again as the specified resource group would not exist.

This PR aims to fix this by checking if the state is stale (the user has a remote state config file but the resource group does not exist) and based on the user's decision, either:

1. Removes the remote config file and continue with a new deployment
2. Or the user can stop the command at this point

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-06-01 14:05 UTC, dudeperf3ct requested changes
Implementation looks solid. Few changes regarding missing docstrings.

2023-06-01 14:05 UTC, dudeperf3ct commented on src/matcha_ml/cli/provision.py
> +            raise typer.Exit()
Docstring for raising this exception

2023-06-01 14:05 UTC, dudeperf3ct commented on src/matcha_ml/cli/provision.py
> +        print("Synced local state config.")
Do we need this line?

2023-06-01 14:05 UTC, dudeperf3ct commented on tests/test_cli/test_provision.py
> +    """_summary_.
Docstrings

2023-06-01 16:29 UTC, swells2020 reviewed
Looks great 👍  One nit and one superfluous (I think) argument.

2023-06-01 16:29 UTC, swells2020 commented on src/matcha_ml/cli/provision.py
> +        print(
Nit: This feels like an important warning message to the user. Could we wrap this in `build_warning_status` from `ui.status_message_builders`?

2023-06-01 16:29 UTC, swells2020 commented on tests/test_cli/test_provision.py
> +    runner: CliRunner, matcha_testing_directory: str, mock_use_lock: MagicMock
Do we need to pass `mock_use_lock` to the test?

2023-06-02 09:52 UTC, dudeperf3ct approved these changes
LGTM! Awesome @Christopher-Norman

2023-06-02 10:05 UTC, JonoCX approved these changes
Nice work! 🚀  

See couple of nits

2023-06-02 10:05 UTC, JonoCX commented on src/matcha_ml/cli/provision.py
> +        if not remove_local_config:
Nit: could be a one-liner if:

```python
if not typer.confirm("..."):
```

2023-06-02 10:20 UTC, JonoCX approved these changes
LGTM

2023-06-02 10:21 UTC, merged