[RPD-237] Add a check for the user and environment uuid
fuzzylabs/matcha pull request #136
Opened 2023-06-01 14:11 UTC by JonoCX

This PR introduces a validation check for the uuid's that we're generating (one for the user and one for the matcha environment). The check is simple, if the parsed ID can be used to create a `UUID` object then we know it's a valid UUID.

We're introducing this check as there's a possibly a user could inadvertently modify the two ids, which is something that want to avoid for obvious reasons.

If the potential uuid can be parsed as a UUID object, then the function returns `True`, otherwise an error is raised.

These checks have been added into the code where relevant and tests have been updated accordingly, more precisely:

* A `_check_uuid` function has been introduced in a new `_validation` file under `services`.
* Checks have been added to the `analytics_service` and `global_parameter_service`.
* A `conftest` has been added to the `test_services` module to generate a uuid for the relevant tests.
* Finally, the tests that make use of a uuid have been updated to use the above uuid.

## Checklist

Please ensure you have done the following:

* [x] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [x] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [x] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-06-01 16:46 UTC, swells2020 requested changes
Looks great 🦖 . I've flagged a few docstrings and a few nits.

2023-06-02 06:43 UTC, JonoCX commented on src/matcha_ml/services/_validation.py
> +UUID_VERSION = 4
I'd prefer to make use of constant variables vs. including `4` in the constructor for a UUID. The UUID generated in `global_parameter_service` is the same, it's create a uuid4 but using the shortcut function. Here, we need to use the constructor to check whether the `uuid` parameter is valid or not, we're not aiming to just generate a uuid

2023-06-02 09:23 UTC, Christopher-Norman approved these changes
Looking good, just one possible typo and then ready to go

2023-06-02 09:23 UTC, Christopher-Norman commented on src/matcha_ml/services/_validation.py
> +            "Error - the user or environment unique identifier is maliformed."
Is this meant to be "malformed"?

2023-06-02 10:19 UTC, merged