[BUG] RPD-254 no state file after destroying resources
fuzzylabs/matcha pull request #154
Opened 2023-06-14 15:22 UTC by KirsoppJ

… code.

_Write a short description which explains what this pull request does and, briefly, how._

_If new dependencies are introduced to the project, please list them here:_

* _new dependency_

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-06-15 13:53 UTC, JonoCX reviewed
Nice work - currently waiting on manual testing locally to work prior to approving

2023-06-19 09:27 UTC, Christopher-Norman requested changes
When testing these changes I seem to get the following error at the end of running `matcha destroy`:
```
⏳ Destroying Remote State resources...

⠦ 0:00:56 Destroying
Error while creating Azure Storage client: Error while loading state configuration: [Errno 2] No such file or directory: 
'/Users/user/matcha/matcha.config.json'
```
Can we fix this error too?

2023-06-19 09:51 UTC, JonoCX approved these changes
LGTM!

2023-06-20 07:37 UTC, JonoCX commented
> When testing these changes I seem to get the following error at the end of running `matcha destroy`:
> 
> ```
> ⏳ Destroying Remote State resources...
> 
> ⠦ 0:00:56 Destroying
> Error while creating Azure Storage client: Error while loading state configuration: [Errno 2] No such file or directory: 
> '/Users/user/matcha/matcha.config.json'
> ```
> 
> Can we fix this error too?

@KirsoppJ is investigating this in a separate ticket - I don't believe this bug has been brought in by the changes in this PR

2023-06-21 08:59 UTC, JonoCX approved these changes
LGTM!

This has flagged a couple of bugs which are going to be dealt with in separate tickets.

2023-06-21 09:46 UTC, merged