Rpd 287 zenml version inference for zenserver
fuzzylabs/matcha pull request #180
Opened 2023-07-31 15:47 UTC by KirsoppJ

This PR has matcha look for a local install of zenml in the environment from which it was launched, then sets the version to be installed on the remote resources accordingly. If no installation is found, then the most recent release of zen server is installed instead.

Most of the changes are to terraform files, where a new variable has been introduced. On the python side, the version is passed to `build_template_configuration` after it is inferred by new `infer_zenml_version` function. This function also prints to the terminal information regarding the selected zenml version.

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-08-01 07:30 UTC, dudeperf3ct commented on src/matcha_ml/infrastructure/resources/zen_server/main.tf
> +    name = "zenml.version"
This should be `zenml.image.tag`

2023-08-01 07:42 UTC, JonoCX commented
It'd be good if this branch could be merged into an improvement branch: `fixes/` or similar

2023-08-03 12:29 UTC, JonoCX requested changes
LGTM - one minor change to remove old code

2023-08-03 12:29 UTC, JonoCX commented on src/matcha_ml/core/core.py
> +    # zenml_version_is_supported()
No longer needed?

2023-08-03 14:34 UTC, merged