[WIP] [RPD-284] Update AzureRunner to select the Terraform files corresponding to the stack name in the config file
fuzzylabs/matcha pull request #187
Opened 2023-08-08 09:34 UTC by Christopher-Norman

_Write a short description which explains what this pull request does and, briefly, how._

_If new dependencies are introduced to the project, please list them here:_

* _new dependency_

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-08-10 10:48 UTC, KirsoppJ approved these changes
LGTM

2023-08-10 13:25 UTC, JonoCX requested changes
Nice, a couple of architectural changes and we're good to go

2023-08-10 13:40 UTC, Christopher-Norman commented on src/matcha_ml/config/matcha_config.py
> +        except MatchaError:
I think this is fine, defaulting to a `default` stack makes sense and then the config is updated to reflect this default.

2023-08-11 07:22 UTC, JonoCX commented on src/matcha_ml/config/matcha_config.py
> +        except MatchaError:
I agree, it makes sense to default to the default stack when a stack hasn't been set. But from an architectural standpoint, setting the stack within a function that gets the stack doesn't quite make sense as it's mixed functionality. 

I'd be included to return `None` here if no stack can be found, which is a signal to the `provision` function in core to call the `stack_set` function with `stack_name='default'`, e.g.,

```python
# logic in core.provision
if service.get_stack() is None: 
    stack_set(stack_name='default')

...

os.path.join(
    os.path.dirname(__file__),
    os.pardir,
    "infrastructure",
    service.get_stack().value,
)
```

2023-08-11 09:21 UTC, JonoCX approved these changes
LGTM. It'd be good to address the nit to simplify the code a little

2023-08-11 09:33 UTC, Christopher-Norman commented on src/matcha_ml/core/core.py
> +        stack = MatchaConfigService.get_stack()
Also, I believe `lower()` is required as the values are stored in `matcha.config.json` as `LLM` or `DEFAULT`

2023-08-14 07:03 UTC, JonoCX commented on src/matcha_ml/core/core.py
> +        stack = MatchaConfigService.get_stack()
Perhaps adding a type to the `stack` variable in the original implementation may help: `stack: Optional[MatchaConfigComponentProperty] = ...`

On the `lower()`, if the internals are using the stack enum (they should), then the values should all be lower case 

No worries if there's no work around for `mypy`

2023-08-14 10:21 UTC, Christopher-Norman commented on src/matcha_ml/core/core.py
> +        stack = MatchaConfigService.get_stack()
Removed lower casing. No work around for `mypy`.

2023-08-14 10:46 UTC, JonoCX approved these changes
✅ 🌯

2023-08-14 10:47 UTC, merged