[WIP] updates core and azure_runner
fuzzylabs/matcha pull request #188
Opened 2023-08-08 13:40 UTC by swells2020

_Write a short description which explains what this pull request does and, briefly, how._

_If new dependencies are introduced to the project, please list them here:_

* _new dependency_

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-08-09 12:52 UTC, Christopher-Norman requested changes
Added comments

2023-08-09 12:52 UTC, Christopher-Norman commented on tests/test_cli/test_provision.py
> +    print(tf_vars, expected_tf_vars)
Remove print

2023-08-09 12:52 UTC, Christopher-Norman commented on src/matcha_ml/runners/azure_runner.py
is `def _show_terraform_outputs(self, matcha_state: MatchaState) -> None:` going to be removed from this file?

2023-08-09 13:41 UTC, KirsoppJ commented on src/matcha_ml/runners/azure_runner.py
> +        (MatchaStateService): a MatchaStateService instance initialized with Terraform output
indentation

2023-08-09 15:13 UTC, swells2020 commented on src/matcha_ml/runners/azure_runner.py
> +        (MatchaStateService): a MatchaStateService instance initialized with Terraform output
Fixed, ta.

2023-08-09 15:14 UTC, swells2020 commented on tests/test_cli/test_provision.py
> +    print(tf_vars, expected_tf_vars)
Thanks, removed.

2023-08-10 07:29 UTC, Christopher-Norman approved these changes
LGTM 👍

2023-08-10 10:50 UTC, KirsoppJ approved these changes
LGTM

2023-08-10 12:36 UTC, merged