[RPD-286] Add documentation on "stacks" and the new LLM stack
fuzzylabs/matcha pull request #189
Opened 2023-08-08 13:59 UTC by Christopher-Norman

This PR adds a brief section into the docs about "stacks" and what is included in the LLM stack.

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-08-09 09:08 UTC, JonoCX requested changes
Great start 🌯 See comments

2023-08-09 09:32 UTC, Christopher-Norman commented on docs/resources.md
Good shout, updated now

2023-08-09 14:32 UTC, JonoCX requested changes
Nice! 

It feels like the stack subsections are missing something, perhaps more detail a little detail about the two and their components. Plus I think we can link to other parts of the documentation here too, like the API and getting started.

2023-08-09 14:32 UTC, JonoCX commented on docs/resource-stacks.md
> +The `DEFAULT` stack. This stack is ideal for generic machine learning training and deployments and a good starting point. It includes:
Perhaps we could point to the getting started page in this section, as this is the stack that's used there

2023-08-09 14:32 UTC, JonoCX commented on docs/resource-stacks.md
> +## How to switch your stack
Point to the API documentation here too?

2023-08-09 15:02 UTC, KirsoppJ requested changes
Looking great, just a couple of niggles

2023-08-09 15:02 UTC, KirsoppJ commented on docs/resource-stacks.md
> +> Note: These stacks must be set before provisioning any resources and cannot currently be change whilst a deployed.
"whilst a deployed" needs rephrasing

2023-08-09 15:02 UTC, KirsoppJ commented on docs/resource-stacks.md
> +   * [Data Version Control](https://dvc.org/) storage
Don't think we need the link to dvc.org here. The data version control storage is just storage, nothing is installed there.

2023-08-10 12:45 UTC, JonoCX approved these changes
LGTM

2023-08-11 09:21 UTC, merged