[RPD-312] Update base_template/azure_template files to handle new modular Terraform files
fuzzylabs/matcha pull request #209
Opened 2023-08-30 09:10 UTC by Christopher-Norman

This PR adds the functionality for using the modular implementation of Matcha. It mainly updates the `copy_file` function within AzureTemplate class to recursively copy and concatenate Terraform files from the modules to the target destination.

This allows users to add modules to their stack to make a custom stack and provision only the required modules.
```
{"stack": {"name": "custom", "experiment_tracker": "mlflow", "orchestrator": "zenml", "deployer": "seldon", "vector_database": "chroma"}}
```

## Checklist

Please ensure you have done the following:

* [ ] I have read the [CONTRIBUTING](https://github.com/fuzzylabs/matcha/blob/main/CONTRIBUTING.md) guide.
* [ ] I have updated the documentation if required.
* [ ] I have added tests which cover my changes.

## Type of change

Tick all those that apply:

* [ ] Bug Fix (non-breaking change, fixing an issue)
* [ ] New feature (non-breaking change to add functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Other (add details above)

2023-08-30 13:52 UTC, JonoCX requested changes
Nice one - see comment

2023-08-30 13:52 UTC, JonoCX commented on src/matcha_ml/templates/azure_template.py
> +            print(f"Error while emptying directory '{directory}': {e}")
Worth using the `print_error` function in the `ui` module?

2023-08-30 14:51 UTC, Christopher-Norman commented on src/matcha_ml/templates/azure_template.py
> +            print(f"Error while emptying directory '{directory}': {e}")
Updated

2023-08-31 09:16 UTC, JonoCX approved these changes
LGTM 🌯

2023-08-31 10:42 UTC, swells2020 approved these changes
Nice work. LGTM 🔥

2023-08-31 10:42 UTC, merged